import { internalMutation } from "../_generated/server";

export const seedChallenges = internalMutation({
  handler: async (ctx) => {
    // Check if already seeded
    const existing = await ctx.db.query("challenges").first();
    if (existing) {
      console.log("Challenges already seeded, skipping...");
      return;
    }

    const challenges = [
      // ==================== DSA PROBLEMS ====================
      {
        title: "Two Sum",
        slug: "two-sum",
        difficulty: "Easy" as const,
        category: "DSA",
        subcategory: "Arrays & Hashing",
        tags: ["arrays", "hash-map", "two-pointers"],
        description: `## Two Sum\n\nGiven an array of integers \`nums\` and an integer \`target\`, return the indices of the two numbers that add up to the target.\n\nYou may assume that each input has **exactly one solution**, and you may not use the same element twice.\n\nYou can return the answer in any order.`,
        examples: [
          {
            input: "nums = [2,7,11,15], target = 9",
            output: "[0, 1]",
            explanation: "Because nums[0] + nums[1] == 9, we return [0, 1].",
          },
          { input: "nums = [3,2,4], target = 6", output: "[1, 2]" },
        ],
        constraints: [
          "2 <= nums.length <= 10^4",
          "-10^9 <= nums[i] <= 10^9",
          "-10^9 <= target <= 10^9",
          "Only one valid answer exists.",
        ],
        starterCode: {
          python: `def solution(nums, target):\n    """\n    Find two numbers that add up to target.\n    Return their indices.\n    """\n    # Your code here\n    pass`,
          javascript: `function solution(nums, target) {\n    // Find two numbers that add up to target\n    // Return their indices\n}`,
          typescript: `function solution(nums: number[], target: number): number[] {\n    // Find two numbers that add up to target\n    // Return their indices\n}`,
        },
        driverCode: {
          python: `_result = solution({{TEST_INPUT}})\nif sorted(_result) == sorted({{EXPECTED_OUTPUT}}):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={{EXPECTED_OUTPUT}}:actual={_result}:0")`,
          javascript: `const _result = solution({{TEST_INPUT}});\nconst _expected = {{EXPECTED_OUTPUT}};\nif (JSON.stringify(_result.sort((a,b)=>a-b)) === JSON.stringify(_expected.sort((a,b)=>a-b))) {\n    console.log("PASS:{{TEST_ID}}:0");\n} else {\n    console.log("FAIL:{{TEST_ID}}:expected=" + JSON.stringify(_expected) + ":actual=" + JSON.stringify(_result) + ":0");\n}`,
        },
        testCases: [
          { id: "tc1", input: "[2,7,11,15], 9", expectedOutput: "[0,1]", isHidden: false },
          { id: "tc2", input: "[3,2,4], 6", expectedOutput: "[1,2]", isHidden: false },
          { id: "tc3", input: "[3,3], 6", expectedOutput: "[0,1]", isHidden: false },
          { id: "tc4", input: "[1,5,3,7,2,8], 10", expectedOutput: "[1,3]", isHidden: true },
          { id: "tc5", input: "[-1,-2,-3,-4,-5], -8", expectedOutput: "[2,4]", isHidden: true },
        ],
        hints: [
          "A brute force approach would be O(n²). Can you do better?",
          "Think about using a hash map to store values you've seen.",
          "For each element, check if (target - element) exists in your hash map.",
        ],
        editorial: `## Solution\n\n### Approach: Hash Map\n\nUse a hash map to store each number's index as we iterate. For each number, check if \`target - num\` is in the map.\n\n\`\`\`python\ndef solution(nums, target):\n    seen = {}\n    for i, num in enumerate(nums):\n        complement = target - num\n        if complement in seen:\n            return [seen[complement], i]\n        seen[num] = i\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(n)`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 49.2,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 1,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Valid Parentheses",
        slug: "valid-parentheses",
        difficulty: "Easy" as const,
        category: "DSA",
        subcategory: "Stacks",
        tags: ["stack", "string", "fundamentals"],
        description: `## Valid Parentheses\n\nGiven a string \`s\` containing just the characters \`'('\`, \`')'\`, \`'{'\`, \`'}'\`, \`'['\` and \`']'\`, determine if the input string is valid.\n\nAn input string is valid if:\n1. Open brackets must be closed by the same type of brackets.\n2. Open brackets must be closed in the correct order.\n3. Every close bracket has a corresponding open bracket of the same type.`,
        examples: [
          { input: 's = "()"', output: "true" },
          { input: 's = "()[]{}"', output: "true" },
          { input: 's = "(]"', output: "false" },
        ],
        constraints: [
          "1 <= s.length <= 10^4",
          "s consists of parentheses only '()[]{}'",
        ],
        starterCode: {
          python: `def solution(s):\n    """\n    Determine if the input string has valid parentheses.\n    """\n    # Your code here\n    pass`,
          javascript: `function solution(s) {\n    // Determine if the input string has valid parentheses\n}`,
        },
        driverCode: {
          python: `_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif str(_result).lower() == str(_expected).lower():\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
          javascript: `const _result = solution({{TEST_INPUT}});\nconst _expected = {{EXPECTED_OUTPUT}};\nif (String(_result) === String(_expected)) {\n    console.log("PASS:{{TEST_ID}}:0");\n} else {\n    console.log("FAIL:{{TEST_ID}}:expected=" + _expected + ":actual=" + _result + ":0");\n}`,
        },
        testCases: [
          { id: "tc1", input: '"()"', expectedOutput: "true", isHidden: false },
          { id: "tc2", input: '"()[]{}"', expectedOutput: "true", isHidden: false },
          { id: "tc3", input: '"(]"', expectedOutput: "false", isHidden: false },
          { id: "tc4", input: '"([{}])"', expectedOutput: "true", isHidden: true },
          { id: "tc5", input: '""', expectedOutput: "true", isHidden: true },
        ],
        hints: [
          "Use a stack to keep track of opening brackets.",
          "When you encounter a closing bracket, check if it matches the top of the stack.",
        ],
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 40.1,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 2,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Merge Two Sorted Lists",
        slug: "merge-two-sorted-lists",
        difficulty: "Easy" as const,
        category: "DSA",
        subcategory: "Linked Lists",
        tags: ["linked-list", "recursion", "two-pointers"],
        description: `## Merge Two Sorted Lists\n\nYou are given two sorted arrays \`list1\` and \`list2\`. Merge them into a single sorted array.\n\nReturn the merged sorted array.`,
        examples: [
          { input: "list1 = [1,2,4], list2 = [1,3,4]", output: "[1,1,2,3,4,4]" },
          { input: "list1 = [], list2 = [0]", output: "[0]" },
        ],
        constraints: [
          "0 <= list length <= 50",
          "-100 <= values <= 100",
          "Both lists are sorted in non-decreasing order",
        ],
        starterCode: {
          python: `def solution(list1, list2):\n    """\n    Merge two sorted lists into one sorted list.\n    """\n    # Your code here\n    pass`,
          javascript: `function solution(list1, list2) {\n    // Merge two sorted lists into one sorted list\n}`,
        },
        driverCode: {
          python: `_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif list(_result) == list(_expected):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
          javascript: `const _result = solution({{TEST_INPUT}});\nconst _expected = {{EXPECTED_OUTPUT}};\nif (JSON.stringify(_result) === JSON.stringify(_expected)) {\n    console.log("PASS:{{TEST_ID}}:0");\n} else {\n    console.log("FAIL:{{TEST_ID}}:expected=" + JSON.stringify(_expected) + ":actual=" + JSON.stringify(_result) + ":0");\n}`,
        },
        testCases: [
          { id: "tc1", input: "[1,2,4], [1,3,4]", expectedOutput: "[1,1,2,3,4,4]", isHidden: false },
          { id: "tc2", input: "[], [0]", expectedOutput: "[0]", isHidden: false },
          { id: "tc3", input: "[], []", expectedOutput: "[]", isHidden: true },
          { id: "tc4", input: "[1,3,5,7], [2,4,6,8]", expectedOutput: "[1,2,3,4,5,6,7,8]", isHidden: true },
        ],
        hints: [
          "Use two pointers, one for each list.",
          "Compare elements at both pointers and take the smaller one.",
        ],
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 62.3,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 3,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Binary Search",
        slug: "binary-search",
        difficulty: "Easy" as const,
        category: "DSA",
        subcategory: "Binary Search",
        tags: ["binary-search", "arrays", "fundamentals"],
        description: `## Binary Search\n\nGiven a sorted array of integers \`nums\` and a \`target\`, write a function that returns the index of the target if found, otherwise return \`-1\`.\n\nYou must write an algorithm with **O(log n)** runtime complexity.`,
        examples: [
          {
            input: "nums = [-1,0,3,5,9,12], target = 9",
            output: "4",
            explanation: "9 exists in nums and its index is 4.",
          },
          {
            input: "nums = [-1,0,3,5,9,12], target = 2",
            output: "-1",
            explanation: "2 does not exist in nums so return -1.",
          },
        ],
        constraints: [
          "1 <= nums.length <= 10^4",
          "All integers in nums are unique",
          "nums is sorted in ascending order",
        ],
        starterCode: {
          python: `def solution(nums, target):\n    """\n    Find target in sorted array using binary search.\n    Return index or -1 if not found.\n    """\n    # Your code here\n    pass`,
          javascript: `function solution(nums, target) {\n    // Find target in sorted array using binary search\n    // Return index or -1 if not found\n}`,
        },
        driverCode: {
          python: `_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif _result == _expected:\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
          javascript: `const _result = solution({{TEST_INPUT}});\nconst _expected = {{EXPECTED_OUTPUT}};\nif (_result === _expected) {\n    console.log("PASS:{{TEST_ID}}:0");\n} else {\n    console.log("FAIL:{{TEST_ID}}:expected=" + _expected + ":actual=" + _result + ":0");\n}`,
        },
        testCases: [
          { id: "tc1", input: "[-1,0,3,5,9,12], 9", expectedOutput: "4", isHidden: false },
          { id: "tc2", input: "[-1,0,3,5,9,12], 2", expectedOutput: "-1", isHidden: false },
          { id: "tc3", input: "[5], 5", expectedOutput: "0", isHidden: true },
          { id: "tc4", input: "[1,2,3,4,5,6,7,8,9,10], 7", expectedOutput: "6", isHidden: true },
        ],
        hints: [
          "Use two pointers for left and right bounds.",
          "Calculate mid and compare with target to decide which half to search.",
        ],
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 55.8,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 4,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Maximum Subarray (Kadane's Algorithm)",
        slug: "maximum-subarray",
        difficulty: "Medium" as const,
        category: "DSA",
        subcategory: "Dynamic Programming",
        tags: ["dynamic-programming", "arrays", "greedy"],
        description: `## Maximum Subarray\n\nGiven an integer array \`nums\`, find the subarray with the largest sum, and return its sum.\n\nA **subarray** is a contiguous non-empty sequence of elements within an array.`,
        examples: [
          {
            input: "nums = [-2,1,-3,4,-1,2,1,-5,4]",
            output: "6",
            explanation: "The subarray [4,-1,2,1] has the largest sum 6.",
          },
          { input: "nums = [1]", output: "1" },
        ],
        constraints: [
          "1 <= nums.length <= 10^5",
          "-10^4 <= nums[i] <= 10^4",
        ],
        starterCode: {
          python: `def solution(nums):\n    """\n    Find the contiguous subarray with the largest sum.\n    """\n    # Your code here\n    pass`,
          javascript: `function solution(nums) {\n    // Find the contiguous subarray with the largest sum\n}`,
        },
        driverCode: {
          python: `_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif _result == _expected:\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
          javascript: `const _result = solution({{TEST_INPUT}});\nconst _expected = {{EXPECTED_OUTPUT}};\nif (_result === _expected) {\n    console.log("PASS:{{TEST_ID}}:0");\n} else {\n    console.log("FAIL:{{TEST_ID}}:expected=" + _expected + ":actual=" + _result + ":0");\n}`,
        },
        testCases: [
          { id: "tc1", input: "[-2,1,-3,4,-1,2,1,-5,4]", expectedOutput: "6", isHidden: false },
          { id: "tc2", input: "[1]", expectedOutput: "1", isHidden: false },
          { id: "tc3", input: "[5,4,-1,7,8]", expectedOutput: "23", isHidden: false },
          { id: "tc4", input: "[-1]", expectedOutput: "-1", isHidden: true },
          { id: "tc5", input: "[-2,-1]", expectedOutput: "-1", isHidden: true },
        ],
        hints: [
          "Think about Kadane's algorithm.",
          "At each position, decide whether to extend the current subarray or start a new one.",
        ],
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 50.1,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 5,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Top K Frequent Elements",
        slug: "top-k-frequent-elements",
        difficulty: "Medium" as const,
        category: "DSA",
        subcategory: "Arrays & Hashing",
        tags: ["arrays", "hash-map", "sorting", "heap"],
        description: `## Top K Frequent Elements\n\nGiven an integer array \`nums\` and an integer \`k\`, return the \`k\` most frequent elements.\n\nYou may return the answer in **any order**.`,
        examples: [
          {
            input: "nums = [1,1,1,2,2,3], k = 2",
            output: "[1,2]",
            explanation: "1 appears 3 times and 2 appears 2 times.",
          },
          { input: "nums = [1], k = 1", output: "[1]" },
        ],
        constraints: [
          "1 <= nums.length <= 10^5",
          "-10^4 <= nums[i] <= 10^4",
          "1 <= k <= number of unique elements",
        ],
        starterCode: {
          python: `def solution(nums, k):\n    \"\"\"\n    Return the k most frequent elements.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(nums, k) {\n    // Return the k most frequent elements\n}`,
          typescript: `function solution(nums: number[], k: number): number[] {\n    // Return the k most frequent elements\n}`,
        },
        driverCode: {
          python: `_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif sorted(list(_result)) == sorted(list(_expected)):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
          javascript: `const _result = solution({{TEST_INPUT}});\nconst _expected = {{EXPECTED_OUTPUT}};\nconst _a = Array.from(_result).sort((a, b) => a - b);\nconst _b = Array.from(_expected).sort((a, b) => a - b);\nif (JSON.stringify(_a) === JSON.stringify(_b)) {\n    console.log("PASS:{{TEST_ID}}:0");\n} else {\n    console.log("FAIL:{{TEST_ID}}:expected=" + JSON.stringify(_expected) + ":actual=" + JSON.stringify(_result) + ":0");\n}`,
        },
        testCases: [
          { id: "tc1", input: "[1,1,1,2,2,3], 2", expectedOutput: "[1,2]", isHidden: false },
          { id: "tc2", input: "[4,4,4,5,5,6], 1", expectedOutput: "[4]", isHidden: false },
          { id: "tc3", input: "[1,1,2,3,3,3], 2", expectedOutput: "[3,1]", isHidden: true },
          { id: "tc4", input: "[-1,-1,-2,-2,-2,3], 2", expectedOutput: "[-2,-1]", isHidden: true },
        ],
        hints: [
          "Build a frequency map of each value.",
          "A heap or bucket sort can find the top k efficiently.",
        ],
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 47.6,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 6,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Longest Substring Without Repeating Characters",
        slug: "longest-substring-without-repeating-characters",
        difficulty: "Medium" as const,
        category: "DSA",
        subcategory: "Sliding Window",
        tags: ["string", "sliding-window", "hash-set"],
        description: `## Longest Substring Without Repeating Characters\n\nGiven a string \`s\`, find the length of the longest substring without repeating characters.`,
        examples: [
          { input: 's = "abcabcbb"', output: "3", explanation: "The answer is \"abc\"." },
          { input: 's = "bbbbb"', output: "1", explanation: "The answer is \"b\"." },
        ],
        constraints: [
          "0 <= s.length <= 10^5",
          "s consists of printable ASCII characters",
        ],
        starterCode: {
          python: `def solution(s):\n    \"\"\"\n    Return the length of the longest substring without repeating characters.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(s) {\n    // Return the length of the longest substring without repeating characters\n}`,
          typescript: `function solution(s: string): number {\n    // Return the length of the longest substring without repeating characters\n}`,
        },
        driverCode: {
          python: `_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif _result == _expected:\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
          javascript: `const _result = solution({{TEST_INPUT}});\nconst _expected = {{EXPECTED_OUTPUT}};\nif (_result === _expected) {\n    console.log("PASS:{{TEST_ID}}:0");\n} else {\n    console.log("FAIL:{{TEST_ID}}:expected=" + _expected + ":actual=" + _result + ":0");\n}`,
        },
        testCases: [
          { id: "tc1", input: '"abcabcbb"', expectedOutput: "3", isHidden: false },
          { id: "tc2", input: '"bbbbb"', expectedOutput: "1", isHidden: false },
          { id: "tc3", input: '"pwwkew"', expectedOutput: "3", isHidden: false },
          { id: "tc4", input: '""', expectedOutput: "0", isHidden: true },
          { id: "tc5", input: '"dvdf"', expectedOutput: "3", isHidden: true },
        ],
        hints: [
          "Use a sliding window with a set or map to track last seen positions.",
          "When a duplicate appears, move the left pointer past the previous index.",
        ],
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 45.2,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 7,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Climbing Stairs",
        slug: "climbing-stairs",
        difficulty: "Easy" as const,
        category: "DSA",
        subcategory: "Dynamic Programming",
        tags: ["dynamic-programming", "memoization", "fibonacci"],
        description: `## Climbing Stairs\n\nYou are climbing a staircase. It takes \`n\` steps to reach the top. Each time you can climb 1 or 2 steps.\n\nHow many distinct ways can you climb to the top?`,
        examples: [
          { input: "n = 2", output: "2", explanation: "(1+1) and (2)." },
          { input: "n = 3", output: "3", explanation: "(1+1+1), (1+2), (2+1)." },
        ],
        constraints: [
          "1 <= n <= 45",
        ],
        starterCode: {
          python: `def solution(n):\n    \"\"\"\n    Return the number of distinct ways to climb to the top.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(n) {\n    // Return the number of distinct ways to climb to the top\n}`,
          typescript: `function solution(n: number): number {\n    // Return the number of distinct ways to climb to the top\n}`,
        },
        driverCode: {
          python: `_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif _result == _expected:\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
          javascript: `const _result = solution({{TEST_INPUT}});\nconst _expected = {{EXPECTED_OUTPUT}};\nif (_result === _expected) {\n    console.log("PASS:{{TEST_ID}}:0");\n} else {\n    console.log("FAIL:{{TEST_ID}}:expected=" + _expected + ":actual=" + _result + ":0");\n}`,
        },
        testCases: [
          { id: "tc1", input: "2", expectedOutput: "2", isHidden: false },
          { id: "tc2", input: "3", expectedOutput: "3", isHidden: false },
          { id: "tc3", input: "4", expectedOutput: "5", isHidden: false },
          { id: "tc4", input: "1", expectedOutput: "1", isHidden: true },
          { id: "tc5", input: "10", expectedOutput: "89", isHidden: true },
        ],
        hints: [
          "This is a Fibonacci-style recurrence: ways(n) = ways(n-1) + ways(n-2).",
          "Use O(1) space by keeping only the last two values.",
        ],
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 63.1,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 8,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },

      // ==================== AI/ML PROBLEMS ====================
      {
        title: "Linear Regression from Scratch",
        slug: "linear-regression-from-scratch",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Linear Regression",
        tags: ["numpy", "regression", "normal-equation", "fundamentals"],
        description: `## Linear Regression from Scratch\n\nImplement simple linear regression using the **Normal Equation**.\n\nGiven training data \`X\` (features) and \`y\` (targets), compute the optimal weights and return predictions.\n\n### The Normal Equation\n**θ = (XᵀX)⁻¹ Xᵀy**\n\n### Steps:\n1. Add a bias column of ones to X\n2. Compute weights θ using the normal equation\n3. Return predictions: **ŷ = X_b · θ**`,
        examples: [
          {
            input: "X = [[1],[2],[3]], y = [2,4,6]",
            output: "[2.0, 4.0, 6.0]",
            explanation: "Perfect linear relationship y = 2x. Model learns exact weights.",
          },
        ],
        constraints: [
          "Use only NumPy (no sklearn)",
          "X: 2D numpy array (n_samples, n_features)",
          "y: 1D numpy array (n_samples,)",
          "Return 1D numpy array of predictions",
          "Tolerance: 1e-5 for floating point comparison",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(X, y):\n    """\n    Implement linear regression using the normal equation.\n    \n    Args:\n        X: numpy array of shape (n_samples, n_features) \n        y: numpy array of shape (n_samples,)\n    \n    Returns:\n        predictions: numpy array of shape (n_samples,)\n    """\n    # Your code here\n    pass`,
          javascript: `// This problem requires NumPy - please use Python\nfunction solution(X, y) {\n    throw new Error("Please solve this problem in Python");\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\n_a = np.asarray(_result, dtype=np.float64)\n_b = np.asarray(_expected, dtype=np.float64)\nif np.allclose(_a, _b, rtol=1e-5):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_b.tolist()}:actual={_a.tolist()}:0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([[1],[2],[3]]), np.array([2,4,6])", expectedOutput: "np.array([2.0, 4.0, 6.0])", isHidden: false },
          { id: "tc2", input: "np.array([[1],[2],[3],[4]]), np.array([1,3,5,7])", expectedOutput: "np.array([1.0, 3.0, 5.0, 7.0])", isHidden: false },
          { id: "tc3", input: "np.array([[0],[1],[2],[3],[4]]), np.array([1,1,1,1,1])", expectedOutput: "np.array([1.0,1.0,1.0,1.0,1.0])", isHidden: true },
        ],
        hints: [
          "Add a bias column: X_b = np.c_[np.ones((X.shape[0], 1)), X]",
          "Normal equation: theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y",
          "Predictions: y_pred = X_b @ theta",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(X, y):\n    X_b = np.c_[np.ones((X.shape[0], 1)), X]\n    theta = np.linalg.inv(X_b.T @ X_b) @ X_b.T @ y\n    return X_b @ theta\n\`\`\`\n\n**Time Complexity:** O(n·d² + d³)  \n**Space Complexity:** O(d²)`,
        timeLimit: 10000,
        memoryLimit: 512,
        acceptanceRate: 72.5,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 101,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Sigmoid Activation Function",
        slug: "sigmoid-activation-function",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Neural Networks",
        tags: ["numpy", "activation-functions", "neural-networks", "fundamentals"],
        description: `## Sigmoid Activation Function\n\nImplement the **sigmoid function** and its **derivative**.\n\n### Formulas:\n- Sigmoid: **σ(x) = 1 / (1 + e^(-x))**\n- Derivative: **σ'(x) = σ(x) · (1 - σ(x))**\n\nYour function should return a **tuple**: \`(sigmoid_output, derivative_output)\`.\n\n> ⚠️ Make sure to handle very large/small inputs without numerical overflow.`,
        examples: [
          {
            input: "x = np.array([0.0])",
            output: "(np.array([0.5]), np.array([0.25]))",
            explanation: "σ(0) = 0.5, σ'(0) = 0.5 * (1-0.5) = 0.25",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Input: numpy array of any shape",
          "Return: tuple of two numpy arrays with same shape",
          "Handle inputs in range [-1000, 1000] without overflow",
          "Tolerance: 1e-5",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(x):\n    """\n    Compute sigmoid and its derivative.\n    \n    Args:\n        x: numpy array\n    \n    Returns:\n        tuple: (sigmoid(x), sigmoid_derivative(x))\n    """\n    # Your code here\n    pass`,
          javascript: `function solution(x) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_sig, _der = solution({{TEST_INPUT}})\n_e_sig, _e_der = {{EXPECTED_OUTPUT}}\n_sig = np.asarray(_sig, dtype=np.float64)\n_der = np.asarray(_der, dtype=np.float64)\n_e_sig = np.asarray(_e_sig, dtype=np.float64)\n_e_der = np.asarray(_e_der, dtype=np.float64)\nif np.allclose(_sig, _e_sig, rtol=1e-5) and np.allclose(_der, _e_der, rtol=1e-5):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected=({_e_sig.tolist()},{_e_der.tolist()}):actual=({_sig.tolist()},{_der.tolist()}):0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([0.0])", expectedOutput: "(np.array([0.5]), np.array([0.25]))", isHidden: false },
          { id: "tc2", input: "np.array([1.0, -1.0])", expectedOutput: "(np.array([0.7310585, 0.2689414]), np.array([0.1966119, 0.1966119]))", isHidden: false },
          { id: "tc3", input: "np.array([1000])", expectedOutput: "(np.array([1.0]), np.array([0.0]))", isHidden: true },
        ],
        hints: [
          "Use np.clip to handle overflow: clip x to a safe range before computing exp.",
          "The derivative is simply sigmoid * (1 - sigmoid).",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(x):\n    x = np.clip(x, -500, 500)\n    sig = 1 / (1 + np.exp(-x))\n    der = sig * (1 - sig)\n    return sig, der\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(1) extra`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 85.3,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 102,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "K-Nearest Neighbors Classifier",
        slug: "knn-classifier",
        difficulty: "Medium" as const,
        category: "AI/ML",
        subcategory: "Classification",
        tags: ["numpy", "knn", "classification", "distance-metrics"],
        description: `## K-Nearest Neighbors Classifier\n\nImplement a **K-Nearest Neighbors (KNN)** classifier from scratch.\n\nGiven training data \`X_train\`, \`y_train\`, test data \`X_test\`, and parameter \`k\`, predict the labels for the test data.\n\n### Algorithm:\n1. For each test point, compute Euclidean distance to all training points\n2. Find the k nearest neighbors\n3. Return the most common label among those neighbors`,
        examples: [
          {
            input: "X_train = [[0,0],[1,1],[2,2]], y_train = [0,0,1], X_test = [[0.5,0.5]], k = 2",
            output: "[0]",
            explanation: "The 2 nearest neighbors to [0.5,0.5] are [0,0] and [1,1], both labeled 0.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Use Euclidean distance",
          "For ties, choose the smaller label",
          "1 <= k <= len(X_train)",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(X_train, y_train, X_test, k):\n    """\n    Implement KNN classifier.\n    \n    Args:\n        X_train: numpy array (n_train, n_features)\n        y_train: numpy array (n_train,)\n        X_test: numpy array (n_test, n_features)\n        k: int, number of neighbors\n    \n    Returns:\n        predictions: numpy array (n_test,)\n    """\n    # Your code here\n    pass`,
          javascript: `function solution(X_train, y_train, X_test, k) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif np.array_equal(np.array(_result), np.array(_expected)):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={list(_expected)}:actual={list(_result)}:0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([[0,0],[1,1],[2,2]]), np.array([0,0,1]), np.array([[0.5,0.5]]), 2", expectedOutput: "np.array([0])", isHidden: false },
          { id: "tc2", input: "np.array([[0,0],[1,1],[2,2],[3,3]]), np.array([0,0,1,1]), np.array([[1.5,1.5]]), 3", expectedOutput: "np.array([1])", isHidden: false },
          { id: "tc3", input: "np.array([[0],[1],[2],[3],[4],[5]]), np.array([0,0,0,1,1,1]), np.array([[2.5]]), 5", expectedOutput: "np.array([0])", isHidden: true },
        ],
        hints: [
          "Compute distances: np.linalg.norm(X_test[:, np.newaxis] - X_train, axis=2)",
          "Use np.argsort to find the k nearest neighbors.",
          "Use np.bincount or Counter to find the most common label.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(X_train, y_train, X_test, k):\n    dists = np.linalg.norm(X_test[:, None, :] - X_train[None, :, :], axis=2)\n    idx = np.argsort(dists, axis=1)[:, :k]\n    preds = []\n    for row in idx:\n        votes = y_train[row]\n        counts = np.bincount(votes)\n        preds.append(int(np.argmax(counts)))\n    return np.array(preds)\n\`\`\`\n\n**Time Complexity:** O(n_test * n_train * d)  \n**Space Complexity:** O(n_test * n_train)`,
        timeLimit: 10000,
        memoryLimit: 512,
        acceptanceRate: 58.7,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 103,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Softmax Function",
        slug: "softmax-function",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Neural Networks",
        tags: ["numpy", "softmax", "activation-functions", "numerical-stability"],
        description: `## Softmax Function\n\nImplement the **softmax** function for a 2D NumPy array.\n\nGiven \`X\` of shape \`(n_samples, n_features)\`, return the row-wise softmax so each row sums to 1.\n\nUse a numerically stable implementation.`,
        examples: [
          {
            input: "X = np.array([[1.0, 2.0, 3.0]])",
            output: "np.array([[0.09003057, 0.24472847, 0.66524096]])",
            explanation: "Softmax probabilities for a single row.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "X is a 2D numpy array",
          "Return a 2D numpy array with the same shape as X",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(X):\n    \"\"\"\n    Compute row-wise softmax for a 2D array.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(X) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\n_a = np.asarray(_result, dtype=np.float64)\n_b = np.asarray(_expected, dtype=np.float64)\nif np.allclose(_a, _b, rtol=1e-6, atol=1e-7):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_b.tolist()}:actual={_a.tolist()}:0")`,
        },
        testCases: [
          {
            id: "tc1",
            input: "np.array([[1.0, 2.0, 3.0]])",
            expectedOutput: "np.array([[0.09003057, 0.24472847, 0.66524096]])",
            isHidden: false,
          },
          {
            id: "tc2",
            input: "np.array([[0.0, 0.0],[1.0, 2.0]])",
            expectedOutput: "np.array([[0.5, 0.5],[0.26894142, 0.73105858]])",
            isHidden: false,
          },
          {
            id: "tc3",
            input: "np.array([[1000.0, 1000.0]])",
            expectedOutput: "np.array([[0.5, 0.5]])",
            isHidden: true,
          },
        ],
        hints: [
          "Subtract the row-wise max before applying exp for stability.",
          "Normalize by dividing by the row-wise sum of exp values.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(X):\n    X = X - np.max(X, axis=1, keepdims=True)\n    exp = np.exp(X)\n    return exp / np.sum(exp, axis=1, keepdims=True)\n\`\`\`\n\n**Time Complexity:** O(n * d)  \n**Space Complexity:** O(n * d)`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 79.4,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 104,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Mean Squared Error",
        slug: "mean-squared-error",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Loss Functions",
        tags: ["numpy", "loss-function", "regression", "fundamentals"],
        description: `## Mean Squared Error\n\nGiven two NumPy arrays \`y_true\` and \`y_pred\` of equal length, compute the **mean squared error (MSE)**.\n\n**MSE = mean((y_true - y_pred) ** 2)**`,
        examples: [
          {
            input: "y_true = np.array([1,2,3]), y_pred = np.array([1,2,4])",
            output: "0.3333333333333333",
            explanation: "Only the last element differs by 1.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Inputs are 1D numpy arrays of the same length",
          "Return a float",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(y_true, y_pred):\n    \"\"\"\n    Compute mean squared error.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(y_true, y_pred) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif abs(float(_result) - float(_expected)) <= 1e-6:\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
        },
        testCases: [
          {
            id: "tc1",
            input: "np.array([1,2,3]), np.array([1,2,4])",
            expectedOutput: "0.3333333333333333",
            isHidden: false,
          },
          {
            id: "tc2",
            input: "np.array([0.0, 0.0]), np.array([1.0, -1.0])",
            expectedOutput: "1.0",
            isHidden: false,
          },
          {
            id: "tc3",
            input: "np.array([2.5, -0.5, 3.0]), np.array([2.0, 0.0, 3.5])",
            expectedOutput: "0.25",
            isHidden: true,
          },
        ],
        hints: [
          "Use vectorized NumPy operations for subtraction and squaring.",
          "Return the mean of squared differences.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(y_true, y_pred):\n    diff = y_true - y_pred\n    return float(np.mean(diff * diff))\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(1) extra`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 82.7,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 105,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Binary Cross Entropy Loss",
        slug: "binary-cross-entropy-loss",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Loss Functions",
        tags: ["numpy", "loss-function", "classification", "fundamentals"],
        description: `## Binary Cross Entropy Loss\n\nGiven two NumPy arrays \`y_true\` and \`y_pred\` of equal length, compute the **binary cross entropy (BCE)** loss.\n\n**BCE = -mean(y_true * log(y_pred) + (1 - y_true) * log(1 - y_pred))**\n\nClip \`y_pred\` to avoid \`log(0)\`.`,
        examples: [
          {
            input: "y_true = np.array([1,0,1,0]), y_pred = np.array([0.9,0.1,0.8,0.2])",
            output: "0.16425203",
            explanation: "Average negative log-likelihood for the given probabilities.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Inputs are 1D numpy arrays of the same length",
          "y_pred values are probabilities in [0, 1]",
          "Return a float",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(y_true, y_pred):\n    \"\"\"\n    Compute binary cross entropy loss.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(y_true, y_pred) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif abs(float(_result) - float(_expected)) <= 1e-6:\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
        },
        testCases: [
          {
            id: "tc1",
            input: "np.array([1,0,1,0]), np.array([0.9,0.1,0.8,0.2])",
            expectedOutput: "0.16425203",
            isHidden: false,
          },
          {
            id: "tc2",
            input: "np.array([1,1,0,0]), np.array([0.6,0.7,0.4,0.3])",
            expectedOutput: "0.43375025",
            isHidden: false,
          },
          {
            id: "tc3",
            input: "np.array([1,0]), np.array([1.0,0.0])",
            expectedOutput: "0.0",
            isHidden: true,
          },
        ],
        hints: [
          "Clip y_pred with a small epsilon before applying log.",
          "Use vectorized NumPy operations for the loss formula.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(y_true, y_pred):\n    eps = 1e-12\n    y_pred = np.clip(y_pred, eps, 1 - eps)\n    loss = -(y_true * np.log(y_pred) + (1 - y_true) * np.log(1 - y_pred))\n    return float(np.mean(loss))\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(1) extra`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 80.2,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 106,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Feature Standardization (Z-Score)",
        slug: "feature-standardization-zscore",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Preprocessing",
        tags: ["numpy", "preprocessing", "feature-scaling", "fundamentals"],
        description: `## Feature Standardization (Z-Score)\n\nGiven a 2D NumPy array \`X\`, standardize each feature (column) to have mean 0 and standard deviation 1.\n\nIf a column has zero standard deviation, return 0 for that column.`,
        examples: [
          {
            input: "X = np.array([[1,2],[3,4],[5,6]])",
            output: "np.array([[-1.22474487,-1.22474487],[0.0,0.0],[1.22474487,1.22474487]])",
            explanation: "Each column is standardized independently.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "X is a 2D numpy array",
          "Return a 2D numpy array with the same shape as X",
          "Use population standard deviation (ddof=0)",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(X):\n    \"\"\"\n    Standardize features column-wise using Z-score.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(X) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\n_a = np.asarray(_result, dtype=np.float64)\n_b = np.asarray(_expected, dtype=np.float64)\nif np.allclose(_a, _b, rtol=1e-6, atol=1e-7):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_b.tolist()}:actual={_a.tolist()}:0")`,
        },
        testCases: [
          {
            id: "tc1",
            input: "np.array([[1,2],[3,4],[5,6]])",
            expectedOutput: "np.array([[-1.22474487,-1.22474487],[0.0,0.0],[1.22474487,1.22474487]])",
            isHidden: false,
          },
          {
            id: "tc2",
            input: "np.array([[0,1],[0,1]])",
            expectedOutput: "np.array([[0.0,0.0],[0.0,0.0]])",
            isHidden: false,
          },
          {
            id: "tc3",
            input: "np.array([[1,1,1],[2,2,2],[3,3,3]])",
            expectedOutput: "np.array([[-1.22474487,-1.22474487,-1.22474487],[0.0,0.0,0.0],[1.22474487,1.22474487,1.22474487]])",
            isHidden: true,
          },
        ],
        hints: [
          "Compute mean and std per column.",
          "Replace zeros in std with 1 to avoid division by zero.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(X):\n    mean = np.mean(X, axis=0)\n    std = np.std(X, axis=0)\n    std = np.where(std == 0, 1.0, std)\n    return (X - mean) / std\n\`\`\`\n\n**Time Complexity:** O(n * d)  \n**Space Complexity:** O(d)`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 77.9,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 107,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Confusion Matrix (Binary)",
        slug: "confusion-matrix-binary",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Evaluation Metrics",
        tags: ["numpy", "metrics", "classification", "fundamentals"],
        description: `## Confusion Matrix (Binary)\n\nGiven binary labels \`y_true\` and \`y_pred\`, compute the **confusion matrix** in the format:\n\n**[[tn, fp], [fn, tp]]**`,
        examples: [
          {
            input: "y_true = np.array([0,0,1,1]), y_pred = np.array([0,1,0,1])",
            output: "np.array([[1,1],[1,1]])",
            explanation: "One of each: TN, FP, FN, TP.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Inputs are 1D numpy arrays of 0s and 1s",
          "Return a 2x2 numpy array",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(y_true, y_pred):\n    \"\"\"\n    Compute binary confusion matrix as [[tn, fp], [fn, tp]].\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(y_true, y_pred) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif np.array_equal(np.asarray(_result), np.asarray(_expected)):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={list(_expected)}:actual={list(_result)}:0")`,
        },
        testCases: [
          {
            id: "tc1",
            input: "np.array([0,0,1,1]), np.array([0,1,0,1])",
            expectedOutput: "np.array([[1,1],[1,1]])",
            isHidden: false,
          },
          {
            id: "tc2",
            input: "np.array([1,1,1,0]), np.array([1,1,0,0])",
            expectedOutput: "np.array([[1,0],[1,2]])",
            isHidden: false,
          },
          {
            id: "tc3",
            input: "np.array([0,1,0,1]), np.array([0,1,0,1])",
            expectedOutput: "np.array([[2,0],[0,2]])",
            isHidden: true,
          },
        ],
        hints: [
          "Count TN, FP, FN, TP with boolean masks.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(y_true, y_pred):\n    y_true = np.asarray(y_true)\n    y_pred = np.asarray(y_pred)\n    tn = int(np.sum((y_true == 0) & (y_pred == 0)))\n    fp = int(np.sum((y_true == 0) & (y_pred == 1)))\n    fn = int(np.sum((y_true == 1) & (y_pred == 0)))\n    tp = int(np.sum((y_true == 1) & (y_pred == 1)))\n    return np.array([[tn, fp], [fn, tp]])\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(1) extra`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 83.4,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 108,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Cosine Similarity",
        slug: "cosine-similarity",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Vector Similarity",
        tags: ["numpy", "similarity", "vectors", "fundamentals"],
        description: `## Cosine Similarity\n\nGiven two vectors \`a\` and \`b\`, compute their **cosine similarity**.\n\nIf either vector has zero norm, return 0.`,
        examples: [
          {
            input: "a = np.array([1,2,3]), b = np.array([1,2,3])",
            output: "1.0",
            explanation: "Identical vectors have cosine similarity 1.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Inputs are 1D numpy arrays of the same length",
          "Return a float",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(a, b):\n    \"\"\"\n    Compute cosine similarity between vectors a and b.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(a, b) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif abs(float(_result) - float(_expected)) <= 1e-6:\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
        },
        testCases: [
          {
            id: "tc1",
            input: "np.array([1,2,3]), np.array([1,2,3])",
            expectedOutput: "1.0",
            isHidden: false,
          },
          {
            id: "tc2",
            input: "np.array([1,0]), np.array([0,1])",
            expectedOutput: "0.0",
            isHidden: false,
          },
          {
            id: "tc3",
            input: "np.array([1,1]), np.array([-1,-1])",
            expectedOutput: "-1.0",
            isHidden: true,
          },
        ],
        hints: [
          "cos(a,b) = (a dot b) / (||a|| * ||b||)",
          "Handle zero norms to avoid division by zero.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(a, b):\n    a = np.asarray(a)\n    b = np.asarray(b)\n    denom = np.linalg.norm(a) * np.linalg.norm(b)\n    if denom == 0:\n        return 0.0\n    return float(np.dot(a, b) / denom)\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(1) extra`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 84.1,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 109,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "ReLU Activation Function",
        slug: "relu-activation-function",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Neural Networks",
        tags: ["numpy", "activation-functions", "neural-networks", "fundamentals"],
        description: `## ReLU Activation Function\n\nImplement the **ReLU** function and its **derivative**.\n\n### Formulas:\n- ReLU: **f(x) = max(0, x)**\n- Derivative: **f'(x) = 1 if x > 0 else 0**\n\nReturn a **tuple**: \`(relu_output, derivative_output)\`.`,
        examples: [
          {
            input: "x = np.array([-1.0, 0.0, 2.0])",
            output: "(np.array([0.0, 0.0, 2.0]), np.array([0.0, 0.0, 1.0]))",
            explanation: "ReLU zeros out negatives and passes positives.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Input: numpy array of any shape",
          "Return: tuple of two numpy arrays with same shape",
          "Treat derivative at x=0 as 0",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(x):\n    \"\"\"\n    Compute ReLU and its derivative.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(x) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_relu, _der = solution({{TEST_INPUT}})\n_e_relu, _e_der = {{EXPECTED_OUTPUT}}\n_relu = np.asarray(_relu, dtype=np.float64)\n_der = np.asarray(_der, dtype=np.float64)\n_e_relu = np.asarray(_e_relu, dtype=np.float64)\n_e_der = np.asarray(_e_der, dtype=np.float64)\nif np.allclose(_relu, _e_relu, rtol=1e-6) and np.allclose(_der, _e_der, rtol=1e-6):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected=({_e_relu.tolist()},{_e_der.tolist()}):actual=({_relu.tolist()},{_der.tolist()}):0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([-1.0, 0.0, 2.0])", expectedOutput: "(np.array([0.0, 0.0, 2.0]), np.array([0.0, 0.0, 1.0]))", isHidden: false },
          { id: "tc2", input: "np.array([[3.0, -2.0],[0.0, 5.0]])", expectedOutput: "(np.array([[3.0, 0.0],[0.0, 5.0]]), np.array([[1.0, 0.0],[0.0, 1.0]]))", isHidden: false },
          { id: "tc3", input: "np.array([-5.0])", expectedOutput: "(np.array([0.0]), np.array([0.0]))", isHidden: true },
        ],
        hints: [
          "Use np.maximum for ReLU.",
          "The derivative can be computed with a boolean mask.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(x):\n    relu = np.maximum(0, x)\n    der = (x > 0).astype(float)\n    return relu, der\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(1) extra`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 86.8,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 110,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Min-Max Scaling",
        slug: "min-max-scaling",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Preprocessing",
        tags: ["numpy", "preprocessing", "feature-scaling", "fundamentals"],
        description: `## Min-Max Scaling\n\nGiven a 2D NumPy array \`X\`, scale each feature (column) to the range [0, 1].\n\nIf a column has the same min and max, return 0 for that column.`,
        examples: [
          {
            input: "X = np.array([[1,2],[3,4],[5,6]])",
            output: "np.array([[0.0,0.0],[0.5,0.5],[1.0,1.0]])",
            explanation: "Each column is scaled independently.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "X is a 2D numpy array",
          "Return a 2D numpy array with the same shape as X",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(X):\n    \"\"\"\n    Apply min-max scaling column-wise.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(X) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\n_a = np.asarray(_result, dtype=np.float64)\n_b = np.asarray(_expected, dtype=np.float64)\nif np.allclose(_a, _b, rtol=1e-6, atol=1e-7):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_b.tolist()}:actual={_a.tolist()}:0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([[1,2],[3,4],[5,6]])", expectedOutput: "np.array([[0.0,0.0],[0.5,0.5],[1.0,1.0]])", isHidden: false },
          { id: "tc2", input: "np.array([[2,5],[2,10]])", expectedOutput: "np.array([[0.0,0.0],[0.0,1.0]])", isHidden: false },
          { id: "tc3", input: "np.array([[0,0],[1,1]])", expectedOutput: "np.array([[0.0,0.0],[1.0,1.0]])", isHidden: true },
        ],
        hints: [
          "Compute min and max per column.",
          "Avoid division by zero when max equals min.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(X):\n    min_v = np.min(X, axis=0)\n    max_v = np.max(X, axis=0)\n    denom = np.where(max_v - min_v == 0, 1.0, max_v - min_v)\n    return (X - min_v) / denom\n\`\`\`\n\n**Time Complexity:** O(n * d)  \n**Space Complexity:** O(d)`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 78.6,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 111,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "One-Hot Encoding",
        slug: "one-hot-encoding",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Preprocessing",
        tags: ["numpy", "encoding", "preprocessing", "fundamentals"],
        description: `## One-Hot Encoding\n\nGiven a 1D NumPy array of integer labels \`y\` and an integer \`num_classes\`, return a one-hot encoded 2D array.`,
        examples: [
          {
            input: "y = np.array([0,2,1]), num_classes = 3",
            output: "np.array([[1,0,0],[0,0,1],[0,1,0]])",
            explanation: "Each label becomes a one-hot row.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Labels are integers in [0, num_classes-1]",
          "Return shape is (len(y), num_classes)",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(y, num_classes):\n    \"\"\"\n    One-hot encode labels.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(y, num_classes) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif np.array_equal(np.asarray(_result), np.asarray(_expected)):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={list(_expected)}:actual={list(_result)}:0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([0,2,1]), 3", expectedOutput: "np.array([[1,0,0],[0,0,1],[0,1,0]])", isHidden: false },
          { id: "tc2", input: "np.array([1,1,1]), 3", expectedOutput: "np.array([[0,1,0],[0,1,0],[0,1,0]])", isHidden: false },
          { id: "tc3", input: "np.array([2,0]), 4", expectedOutput: "np.array([[0,0,1,0],[1,0,0,0]])", isHidden: true },
        ],
        hints: [
          "Create a zero matrix and set the appropriate indices to 1.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(y, num_classes):\n    y = np.asarray(y, dtype=int)\n    out = np.zeros((len(y), num_classes), dtype=int)\n    out[np.arange(len(y)), y] = 1\n    return out\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(n * c)`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 81.5,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 112,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Accuracy Score",
        slug: "accuracy-score",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Evaluation Metrics",
        tags: ["numpy", "metrics", "classification", "fundamentals"],
        description: `## Accuracy Score\n\nGiven \`y_true\` and \`y_pred\`, compute the **accuracy**: the fraction of correct predictions.`,
        examples: [
          {
            input: "y_true = np.array([1,0,1,1]), y_pred = np.array([1,0,0,1])",
            output: "0.75",
            explanation: "3 out of 4 predictions are correct.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Inputs are 1D numpy arrays of the same length",
          "Return a float",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(y_true, y_pred):\n    \"\"\"\n    Compute accuracy score.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(y_true, y_pred) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif abs(float(_result) - float(_expected)) <= 1e-6:\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([1,0,1,1]), np.array([1,0,0,1])", expectedOutput: "0.75", isHidden: false },
          { id: "tc2", input: "np.array([0,0,0]), np.array([1,0,0])", expectedOutput: "0.6666666667", isHidden: false },
          { id: "tc3", input: "np.array([1,1,1]), np.array([1,1,1])", expectedOutput: "1.0", isHidden: true },
        ],
        hints: [
          "Compute the mean of (y_true == y_pred).",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(y_true, y_pred):\n    return float(np.mean(np.asarray(y_true) == np.asarray(y_pred)))\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(1) extra`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 88.2,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 113,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Precision, Recall, F1 (Binary)",
        slug: "precision-recall-f1-binary",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Evaluation Metrics",
        tags: ["numpy", "metrics", "classification", "fundamentals"],
        description: `## Precision, Recall, F1 (Binary)\n\nGiven binary labels \`y_true\` and \`y_pred\`, compute **precision**, **recall**, and **F1**.\n\nIf a denominator is 0, return 0 for that metric.\n\nReturn a tuple: \`(precision, recall, f1)\`.`,
        examples: [
          {
            input: "y_true = np.array([1,0,1,1]), y_pred = np.array([1,0,0,1])",
            output: "(1.0, 0.6666666667, 0.8)",
            explanation: "TP=2, FP=0, FN=1.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Inputs are 1D numpy arrays of 0s and 1s",
          "Return a tuple of floats",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(y_true, y_pred):\n    \"\"\"\n    Compute precision, recall, and F1 for binary labels.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(y_true, y_pred) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_p, _r, _f1 = solution({{TEST_INPUT}})\n_e_p, _e_r, _e_f1 = {{EXPECTED_OUTPUT}}\nif (abs(float(_p) - float(_e_p)) <= 1e-6 and\n    abs(float(_r) - float(_e_r)) <= 1e-6 and\n    abs(float(_f1) - float(_e_f1)) <= 1e-6):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected=({_e_p},{_e_r},{_e_f1}):actual=({_p},{_r},{_f1}):0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([1,0,1,1]), np.array([1,0,0,1])", expectedOutput: "(1.0, 0.6666666667, 0.8)", isHidden: false },
          { id: "tc2", input: "np.array([0,0,1,1]), np.array([0,1,0,1])", expectedOutput: "(0.5, 0.5, 0.5)", isHidden: false },
          { id: "tc3", input: "np.array([0,1]), np.array([0,0])", expectedOutput: "(0.0, 0.0, 0.0)", isHidden: true },
        ],
        hints: [
          "Compute TP, FP, FN using boolean masks.",
          "F1 = 2 * precision * recall / (precision + recall).",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(y_true, y_pred):\n    y_true = np.asarray(y_true)\n    y_pred = np.asarray(y_pred)\n    tp = np.sum((y_true == 1) & (y_pred == 1))\n    fp = np.sum((y_true == 0) & (y_pred == 1))\n    fn = np.sum((y_true == 1) & (y_pred == 0))\n    precision = 0.0 if (tp + fp) == 0 else tp / (tp + fp)\n    recall = 0.0 if (tp + fn) == 0 else tp / (tp + fn)\n    f1 = 0.0 if (precision + recall) == 0 else 2 * precision * recall / (precision + recall)\n    return float(precision), float(recall), float(f1)\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(1) extra`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 80.8,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 114,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "L2 Normalization (Row-wise)",
        slug: "l2-normalization-row-wise",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Preprocessing",
        tags: ["numpy", "normalization", "preprocessing", "fundamentals"],
        description: `## L2 Normalization (Row-wise)\n\nGiven a 2D NumPy array \`X\`, normalize each row by its L2 norm.\n\nIf a row has zero norm, leave it as zeros.`,
        examples: [
          {
            input: "X = np.array([[3,4],[0,0]])",
            output: "np.array([[0.6,0.8],[0.0,0.0]])",
            explanation: "Row 1 norm is 5, row 2 stays zeros.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "X is a 2D numpy array",
          "Return a 2D numpy array with the same shape as X",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(X):\n    \"\"\"\n    L2-normalize each row.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(X) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\n_a = np.asarray(_result, dtype=np.float64)\n_b = np.asarray(_expected, dtype=np.float64)\nif np.allclose(_a, _b, rtol=1e-6, atol=1e-7):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_b.tolist()}:actual={_a.tolist()}:0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([[3,4],[0,0]])", expectedOutput: "np.array([[0.6,0.8],[0.0,0.0]])", isHidden: false },
          { id: "tc2", input: "np.array([[1,2,2]])", expectedOutput: "np.array([[0.33333333,0.66666667,0.66666667]])", isHidden: false },
          { id: "tc3", input: "np.array([[1,0],[0,1]])", expectedOutput: "np.array([[1.0,0.0],[0.0,1.0]])", isHidden: true },
        ],
        hints: [
          "Compute row-wise norms with np.linalg.norm and keepdims=True.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(X):\n    norms = np.linalg.norm(X, axis=1, keepdims=True)\n    norms = np.where(norms == 0, 1.0, norms)\n    return X / norms\n\`\`\`\n\n**Time Complexity:** O(n * d)  \n**Space Complexity:** O(n)`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 79.1,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 115,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Polynomial Features (1D)",
        slug: "polynomial-features-1d",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Feature Engineering",
        tags: ["numpy", "feature-engineering", "polynomial", "fundamentals"],
        description: `## Polynomial Features (1D)\n\nGiven a 1D NumPy array \`x\` and an integer \`degree\`, return a 2D array with columns \`x^1, x^2, ..., x^degree\`.`,
        examples: [
          {
            input: "x = np.array([1,2,3]), degree = 2",
            output: "np.array([[1,1],[2,4],[3,9]])",
            explanation: "Each row contains powers of x.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "x is a 1D numpy array",
          "degree >= 1",
          "Return shape is (len(x), degree)",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(x, degree):\n    \"\"\"\n    Build polynomial features for 1D input.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(x, degree) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif np.array_equal(np.asarray(_result), np.asarray(_expected)):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={list(_expected)}:actual={list(_result)}:0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([1,2,3]), 2", expectedOutput: "np.array([[1,1],[2,4],[3,9]])", isHidden: false },
          { id: "tc2", input: "np.array([-1,0]), 3", expectedOutput: "np.array([[-1,1,-1],[0,0,0]])", isHidden: false },
          { id: "tc3", input: "np.array([2]), 4", expectedOutput: "np.array([[2,4,8,16]])", isHidden: true },
        ],
        hints: [
          "Stack powers of x from 1 to degree.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(x, degree):\n    x = np.asarray(x)\n    return np.column_stack([x ** p for p in range(1, degree + 1)])\n\`\`\`\n\n**Time Complexity:** O(n * degree)  \n**Space Complexity:** O(n * degree)`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 76.4,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 116,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Pairwise Euclidean Distances",
        slug: "pairwise-euclidean-distances",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Vector Similarity",
        tags: ["numpy", "distance", "vectors", "fundamentals"],
        description: `## Pairwise Euclidean Distances\n\nGiven two 2D arrays \`X\` (n x d) and \`Y\` (m x d), return the pairwise Euclidean distance matrix of shape (n, m).`,
        examples: [
          {
            input: "X = np.array([[0,0],[1,1]]), Y = np.array([[1,0],[2,2]])",
            output: "np.array([[1.0,2.82842712],[1.0,1.41421356]])",
            explanation: "Distances between each row of X and each row of Y.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "X and Y are 2D arrays with the same number of columns",
          "Return a 2D array of floats",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(X, Y):\n    \"\"\"\n    Compute pairwise Euclidean distance matrix.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(X, Y) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\n_a = np.asarray(_result, dtype=np.float64)\n_b = np.asarray(_expected, dtype=np.float64)\nif np.allclose(_a, _b, rtol=1e-6, atol=1e-7):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_b.tolist()}:actual={_a.tolist()}:0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([[0,0],[1,1]]), np.array([[1,0],[2,2]])", expectedOutput: "np.array([[1.0,2.82842712],[1.0,1.41421356]])", isHidden: false },
          { id: "tc2", input: "np.array([[0]]), np.array([[0],[3]])", expectedOutput: "np.array([[0.0,3.0]])", isHidden: false },
          { id: "tc3", input: "np.array([[-1,-1]]), np.array([[1,1]])", expectedOutput: "np.array([[2.82842712]])", isHidden: true },
        ],
        hints: [
          "Use broadcasting: X[:, None, :] - Y[None, :, :].",
          "Compute norm across the last axis.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(X, Y):\n    diff = X[:, None, :] - Y[None, :, :]\n    return np.linalg.norm(diff, axis=2)\n\`\`\`\n\n**Time Complexity:** O(n * m * d)  \n**Space Complexity:** O(n * m * d)`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 74.2,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 117,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Perceptron Prediction",
        slug: "perceptron-prediction",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Linear Models",
        tags: ["numpy", "classification", "perceptron", "fundamentals"],
        description: `## Perceptron Prediction\n\nGiven features \`X\`, weights \`w\`, and bias \`b\`, compute predictions using a perceptron rule:\n\n**pred = 1 if (X·w + b) >= 0 else 0**`,
        examples: [
          {
            input: "X = np.array([[1,1],[2,0],[-1,-1]]), w = np.array([1,1]), b = -1",
            output: "np.array([1,1,0])",
            explanation: "Scores are [1, 1, -3].",
          },
        ],
        constraints: [
          "Use only NumPy",
          "X is 2D (n, d), w is 1D (d,), b is a float",
          "Return a 1D numpy array of 0/1",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(X, w, b):\n    \"\"\"\n    Compute perceptron predictions.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(X, w, b) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif np.array_equal(np.asarray(_result), np.asarray(_expected)):\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={list(_expected)}:actual={list(_result)}:0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([[1,1],[2,0],[-1,-1]]), np.array([1,1]), -1", expectedOutput: "np.array([1,1,0])", isHidden: false },
          { id: "tc2", input: "np.array([[0,0],[1,-1]]), np.array([0.5,0.5]), 0.0", expectedOutput: "np.array([1,1])", isHidden: false },
          { id: "tc3", input: "np.array([[-1,2]]), np.array([1,-2]), 0.0", expectedOutput: "np.array([0])", isHidden: true },
        ],
        hints: [
          "Compute scores with X @ w + b, then threshold at 0.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(X, w, b):\n    scores = X @ w + b\n    return (scores >= 0).astype(int)\n\`\`\`\n\n**Time Complexity:** O(n * d)  \n**Space Complexity:** O(n)`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 82.1,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 118,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
      {
        title: "Mean Absolute Error",
        slug: "mean-absolute-error",
        difficulty: "Easy" as const,
        category: "AI/ML",
        subcategory: "Loss Functions",
        tags: ["numpy", "loss-function", "regression", "fundamentals"],
        description: `## Mean Absolute Error\n\nGiven two NumPy arrays \`y_true\` and \`y_pred\` of equal length, compute the **mean absolute error (MAE)**.\n\n**MAE = mean(|y_true - y_pred|)**`,
        examples: [
          {
            input: "y_true = np.array([1,2,3]), y_pred = np.array([2,2,2])",
            output: "0.6666666667",
            explanation: "Average absolute difference is 2/3.",
          },
        ],
        constraints: [
          "Use only NumPy",
          "Inputs are 1D numpy arrays of the same length",
          "Return a float",
          "Tolerance: 1e-6",
        ],
        starterCode: {
          python: `import numpy as np\n\ndef solution(y_true, y_pred):\n    \"\"\"\n    Compute mean absolute error.\n    \"\"\"\n    # Your code here\n    pass`,
          javascript: `function solution(y_true, y_pred) {\n    // Please solve this problem in Python\n}`,
        },
        driverCode: {
          python: `import numpy as np\n_result = solution({{TEST_INPUT}})\n_expected = {{EXPECTED_OUTPUT}}\nif abs(float(_result) - float(_expected)) <= 1e-6:\n    print(f"PASS:{{TEST_ID}}:0")\nelse:\n    print(f"FAIL:{{TEST_ID}}:expected={_expected}:actual={_result}:0")`,
        },
        testCases: [
          { id: "tc1", input: "np.array([1,2,3]), np.array([2,2,2])", expectedOutput: "0.6666666667", isHidden: false },
          { id: "tc2", input: "np.array([0,0]), np.array([0,0])", expectedOutput: "0.0", isHidden: false },
          { id: "tc3", input: "np.array([1,-1]), np.array([0,1])", expectedOutput: "1.5", isHidden: true },
        ],
        hints: [
          "Use np.abs and np.mean to compute MAE.",
        ],
        editorial: `## Solution\n\n\`\`\`python\nimport numpy as np\n\ndef solution(y_true, y_pred):\n    return float(np.mean(np.abs(y_true - y_pred)))\n\`\`\`\n\n**Time Complexity:** O(n)  \n**Space Complexity:** O(1) extra`,
        timeLimit: 5000,
        memoryLimit: 256,
        acceptanceRate: 84.6,
        totalSubmissions: 0,
        totalAccepted: 0,
        likes: 0,
        dislikes: 0,
        order: 119,
        isPremium: false,
        isPublished: true,
        createdBy: "system",
      },
    ];

    for (const challenge of challenges) {
      await ctx.db.insert("challenges", challenge);
    }

    console.log(`Seeded ${challenges.length} challenges successfully!`);
  },
});
